name: "clinicaltrials-act-converter CI"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: "Unit tests"
        run: py.test
